### ISSUE TITLE
Android downward compatibility with strikt 0.27.0

### ISSUE THREAD

**Issue by nenick** [robfletcher/strikt#229]
Would be great to use this library in Android development but some latest changes aren't compatible with lower Android versions than 24.

    Private interface methods are only supported starting with Android N (--min-api 24): 
    Lstrikt/api/Assertion$Builder;describe(Lkotlin/jvm/functions/Function1;)Ljava/lang/String;

Any ideas to workaround this issue?

**Comment by robfletcher** [comment]
Sounds like it would be worth adding an Android build to the CI matrix. I don't really know the first thing about Android development but it might at least be able to preempt issues like this.

**Comment by robfletcher** [comment]
I've (hopefully) fixed this by making those private interface methods package-level functions instead. I'd love to know how I could replicate this in GitHub Actions so I can avoid regressions.

**Comment by nenick** [comment]
This issues gets reported at "test" compile time. It should be enough to setup a basic android project with strikt as `androidTestImplementation` dependency and call `assembleAndroidTest`. I don't think that making them "privat" will help, but I didn't have tested it yet.

Recently I found that forcing java 8 support does help. Not the best solution but could be an acceptable one.

```
android {
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
}
```

**Comment by robfletcher** [comment]
Well, the commit I made should fix the issue but I'll look into whether I can add an Android sample project or something so that I can stop similar things in future.

Is that because Android defaults to JDK 1.6?

**Comment by nenick** [comment]
Yes, Android still depends on JDK 1.6 until Android 24, then JDK 1.8. The `sourceCompatibility` enables some JDK 1.8 features (including Private interface) but still not all. 

Would be great if `sourceCompatibility = JavaVersion.VERSION_1_8` can be avoided because it's add an extra compile step which does consume extra time.

Next weekend I can also start to contribute some stuff, like a simple android test project. Until there I'm on vacation ;)

**Comment by robfletcher** [comment]
Hmm. Trying to compile Strikt itself with 1.6 compatibility opens up a bunch of errors with the JUnit dependency. Might be resolvable, but given how long 1.6 has been EOLed for now I'm not sure if the effort makes sense.

Any help you could given on Android compatibility would be great. Like I say, it's not my area of expertise. Strikt grew out of my use of Kotlin for cloud microservices, so anything I've built has been largely focused on that use case.

**Comment by nenick** [comment]
> 1.6 compatibility opens up a bunch of errors with the JUnit dependency
For Android we have two test targets. First one are plain JUnit tests on your pc (source compatibility doesn't matter here). The second one are instrumented tests on a device. Google does provide a custom JUnit implementation which does support JDK 1.6 but this is not a usable dependency for plain JUnit tests.

I agree that extra effort for JDK 1.6 makes not much sense. A simple android project which proofs the basic compatibility should be enough here. 

When I understood you correctly then you would also like to get some contributions regarding github actions for Android? I didn't have used github actions yet but I will check what must have to be done for it.

**Comment by robfletcher** [comment]
I think if there's a sample project that could be run alongside the build, that would be fine for GH Actions.
